FROM scratch AS ctx
COPY build_files /

FROM ghcr.io/rhuze-emryk/emryk-ml:latest

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/antigravity-install.sh

RUN bootc container lint
