#!/usr/bin/env bash
# Build-time guard: every file under executable-payload directories must be
# owned by an installed RPM. Protects the RPM-only SBOM coverage from
# silently missing vendor binaries installed outside dnf
# (e.g. `curl | tar -C /usr/local/bin`).
#
# Fails closed: any unowned file fails the build. Legitimate non-RPM files
# must be explicitly justified in ALLOWLIST_REGEX below.
set -euo pipefail

readonly PAYLOAD_DIRS=(
  /usr/bin
  /usr/sbin
  /usr/libexec
  /usr/lib
  /usr/lib64
  /usr/local
  /opt
)

# Known-legitimate non-RPM paths. Each entry must justify why the file is not
# in an RPM and why that's intentional.
readonly ALLOWLIST_REGEX=(
  # The RPM database itself — never package-owned by definition.
  '^/usr/lib/sysimage/rpm/'

  # debuginfo build-id symlinks, generated by post-install scriptlets.
  '^/usr/lib/\.build-id/'

  # Kernel post-install artifacts (dracut initramfs, depmod output, symvers).
  # Created by kernel-core/kernel-modules-* scriptlets, not in the RPM filelist.
  '^/usr/lib/modules/[^/]+/initramfs(-rescue)?\.img$'
  '^/usr/lib/modules/[^/]+/(symvers\.gz|modules\.)'

  # Emryk-built helpers, generated by build.sh / private-ml-install.sh
  # heredocs in this repo. Provenance is the git history of build_files/.
  '^/usr/libexec/emryk/'
  '^/usr/lib/modprobe\.d/blacklist-nouveau\.conf$'

  # rpm-ostree / bootc machinery: tmpfiles configs, rpm macros, prepare-root,
  # base-db snapshot. All generated/owned by the bootc layering system, not
  # individual RPMs.
  '^/usr/lib/rpm-ostree/'
  '^/usr/lib/sysimage/rpm-ostree-base-db/'
  '^/usr/lib/rpm/macros\.d/macros\.rpm-ostree$'
  '^/usr/lib/ostree/prepare-root\.conf$'
  '^/usr/lib/tmpfiles\.d/(rpm-ostree-|90-atomic-desktops-|coredump\.conf)'

  # fontconfig cache, regenerated by fc-cache post-install scriptlets.
  '^/usr/lib/fontconfig/cache/'

  # systemd post-install artifacts: enable-symlinks under .wants/, kinoite/
  # atomic-desktop unit files installed by scriptlets, cgroupify drop-ins
  # for Chrome/Chromium, persistent journald config.
  '^/usr/lib/systemd/system/multi-user\.target\.wants/'
  '^/usr/lib/systemd/system/(fedora-atomic-desktop|fedora-kinoite|run-vmblock|system-systemdx2d|bootloader-update)'
  '^/usr/lib/systemd/system-generators/coreos-sulogin-force-generator$'
  '^/usr/lib/systemd/system-preset/82-kinoite\.preset$'
  '^/usr/lib/systemd/journald\.conf\.d/10-persistent\.conf$'
  '^/usr/lib/systemd/user/app-(chromiumx2dbrowser|glib-chromiumx2dbrowser|glib-googlex2dchrome|gnome-chromiumx2dbrowser|gnome-googlex2dchrome|googlex2dchrome)'

  # Atomic-desktop dracut configs + bootupd JSON manifests, both
  # post-install scriptlet output.
  '^/usr/lib/dracut/dracut\.conf\.d/(10-compression|20-atomic-)'
  '^/usr/lib/bootupd/updates/(BIOS|EFI)\.json$'

  # glibc/nss_db immutable identity files for bootc layout.
  '^/usr/lib/(passwd|group)$'

  # Broadcom NVRAM mapping symlinks created by linux-firmware-whence %post.
  # Filenames legitimately include `:` (vendor:model format).
  '^/usr/lib/firmware/brcm/brcmfmac[0-9]'

  # KNOWN-FALSE-POSITIVES: verified dnf-installed upstream but rpm -qf
  # misreports as unowned in this image type. Revisit if the misreport
  # ever gets root-caused (same class of bug that affected ~5k files when
  # this guard used rpm -qal instead of rpm -qf).
  '^/usr/bin/nvidia-container-toolkit$'                  # akmods nvidia-install.sh NVIDIA_RPMS list
  '^/usr/libexec/fedora-kinoite-plasmalogin-workaround$' # fedora-kinoite-* package
)

# Enumerate candidate files.
find "${PAYLOAD_DIRS[@]}" \( -type f -o -type l \) -print 2>/dev/null \
  | LC_ALL=C sort -u > /tmp/payload-files.txt

# Pre-filter via allowlist to avoid asking rpm about paths we already accept.
while IFS= read -r f; do
  for re in "${ALLOWLIST_REGEX[@]}"; do
    [[ $f =~ $re ]] && continue 2
  done
  printf '%s\n' "$f"
done < /tmp/payload-files.txt > /tmp/payload-to-query.txt

# Ask rpm who owns each file, in batches. rpm -qf prints either the package
# nvra (owned) or "file <path> is not owned by any package" (unowned).
# stderr is folded in to capture "error: file X: No such file ..." for broken
# symlinks; awk discards those by matching only the "is not owned" form.
#
# `|| true` is load-bearing: rpm -qf exits 1 whenever any queried file is
# unowned, which under xargs propagates as exit 123. We don't care about rpm's
# exit status — we only care about its output. Splitting collection from
# parsing keeps `set -e` / pipefail happy.
xargs -r -a /tmp/payload-to-query.txt -L 500 rpm -qf 2>&1 \
  > /tmp/rpm-qf-output.txt || true

awk '/ is not owned by any package$/ {
  sub(/^file /, ""); sub(/ is not owned by any package$/, ""); print
}' /tmp/rpm-qf-output.txt > /tmp/unowned.txt

unowned_count=$(wc -l < /tmp/unowned.txt)
total_scanned=$(wc -l < /tmp/payload-files.txt)
total_queried=$(wc -l < /tmp/payload-to-query.txt)

if (( unowned_count > 0 )); then
  echo >&2 "ERROR: ${unowned_count} payload files are not owned by any RPM"
  echo >&2 "  (scanned ${total_scanned} total; ${total_queried} queried after allowlist):"
  sed >&2 's/^/  /' /tmp/unowned.txt
  echo >&2 ""
  echo >&2 "These would be missed by the RPM-only SBOM. Either install via dnf,"
  echo >&2 "or — if legitimately non-RPM — add to ALLOWLIST_REGEX in"
  echo >&2 "$(basename "$0") with a justification comment."
  exit 1
fi

echo "OK: all ${total_queried} non-allowlisted payload files (of ${total_scanned} scanned) are RPM-owned."
