#!/usr/bin/env bash
# Build-time guard: every file under executable-payload directories must be
# owned by an installed RPM. Protects the RPM-only SBOM coverage from
# silently missing vendor binaries installed outside dnf
# (e.g. `curl | tar -C /usr/local/bin`).
#
# Fails closed: any unowned file fails the build. Legitimate non-RPM files
# must be explicitly justified in ALLOWLIST_REGEX below.
set -euo pipefail

readonly PAYLOAD_DIRS=(
  /usr/bin
  /usr/sbin
  /usr/libexec
  /usr/lib
  /usr/lib64
  /usr/local
  /opt
)

# Known-legitimate non-RPM paths. Each entry must justify why the file is not
# in an RPM and why that's intentional.
readonly ALLOWLIST_REGEX=(
  # The RPM database itself — never package-owned by definition.
  '^/usr/lib/sysimage/rpm/'

  # debuginfo build-id symlinks, generated by post-install scriptlets.
  '^/usr/lib/\.build-id/'

  # Kernel post-install artifacts (dracut initramfs, depmod output, symvers).
  # Created by kernel-core/kernel-modules-* scriptlets, not in the RPM filelist.
  '^/usr/lib/modules/[^/]+/initramfs(-rescue)?\.img$'
  '^/usr/lib/modules/[^/]+/(symvers\.gz|modules\.(dep|symbols|alias|builtin|devname|order)(\.bin)?)$'

  # Emryk-built helpers, generated by build.sh / private-ml-install.sh
  # heredocs in this repo. Provenance is the git history of build_files/.
  '^/usr/libexec/emryk/'
  '^/usr/lib/modprobe\.d/blacklist-nouveau\.conf$'
)

rpm -qal | LC_ALL=C sort -u > /tmp/rpm-owned.txt

find "${PAYLOAD_DIRS[@]}" \( -type f -o -type l \) -print 2>/dev/null \
  | LC_ALL=C sort -u > /tmp/payload-files.txt

comm -23 /tmp/payload-files.txt /tmp/rpm-owned.txt > /tmp/unowned-raw.txt

while IFS= read -r f; do
  for re in "${ALLOWLIST_REGEX[@]}"; do
    [[ $f =~ $re ]] && continue 2
  done
  printf '%s\n' "$f"
done < /tmp/unowned-raw.txt > /tmp/unowned.txt

unowned_count=$(wc -l < /tmp/unowned.txt)

if (( unowned_count > 0 )); then
  echo >&2 "ERROR: ${unowned_count} payload files are not owned by any RPM:"
  sed >&2 's/^/  /' /tmp/unowned.txt
  echo >&2 ""
  echo >&2 "These would be missed by the RPM-only SBOM. Either install via dnf,"
  echo >&2 "or — if legitimately non-RPM — add to ALLOWLIST_REGEX in"
  echo >&2 "$(basename "$0") with a justification comment."
  exit 1
fi

echo "OK: all $(wc -l < /tmp/payload-files.txt) payload files are RPM-owned."
