#!/usr/bin/env bash
# Build-time guard: every file under executable-payload directories must be
# owned by an installed RPM. Protects the RPM-only SBOM coverage from
# silently missing vendor binaries installed outside dnf
# (e.g. `curl | tar -C /usr/local/bin`).
#
# Fails closed: any unowned file fails the build. Legitimate non-RPM files
# must be explicitly justified in ALLOWLIST_REGEX below.
set -euo pipefail

readonly PAYLOAD_DIRS=(
  /usr/bin
  /usr/sbin
  /usr/libexec
  /usr/lib
  /usr/lib64
  /usr/local
  /opt
)

# Known-legitimate non-RPM paths. Each entry must justify why the file is not
# in an RPM and why that's intentional.
readonly ALLOWLIST_REGEX=(
  # The RPM database itself — never package-owned by definition.
  '^/usr/lib/sysimage/rpm/'

  # debuginfo build-id symlinks, generated by post-install scriptlets.
  '^/usr/lib/\.build-id/'

  # Kernel post-install artifacts (dracut initramfs, depmod output, symvers).
  # Created by kernel-core/kernel-modules-* scriptlets, not in the RPM filelist.
  '^/usr/lib/modules/[^/]+/initramfs(-rescue)?\.img$'
  '^/usr/lib/modules/[^/]+/(symvers\.gz|modules\.(dep|symbols|alias|builtin|devname|order)(\.bin)?)$'

  # Emryk-built helpers, generated by build.sh / private-ml-install.sh
  # heredocs in this repo. Provenance is the git history of build_files/.
  '^/usr/libexec/emryk/'
  '^/usr/lib/modprobe\.d/blacklist-nouveau\.conf$'
)

# Enumerate candidate files.
find "${PAYLOAD_DIRS[@]}" \( -type f -o -type l \) -print 2>/dev/null \
  | LC_ALL=C sort -u > /tmp/payload-files.txt

# Pre-filter via allowlist to avoid asking rpm about paths we already accept.
while IFS= read -r f; do
  for re in "${ALLOWLIST_REGEX[@]}"; do
    [[ $f =~ $re ]] && continue 2
  done
  printf '%s\n' "$f"
done < /tmp/payload-files.txt > /tmp/payload-to-query.txt

# Ask rpm who owns each file, in batches. rpm -qf prints either the package
# nvra (owned) or "file <path> is not owned by any package" (unowned).
# stderr is folded in to capture "error: file X: No such file ..." for broken
# symlinks; awk discards those by matching only the "is not owned" form.
#
# `|| true` is load-bearing: rpm -qf exits 1 whenever any queried file is
# unowned, which under xargs propagates as exit 123. We don't care about rpm's
# exit status — we only care about its output. Splitting collection from
# parsing keeps `set -e` / pipefail happy.
xargs -r -a /tmp/payload-to-query.txt -L 500 rpm -qf 2>&1 \
  > /tmp/rpm-qf-output.txt || true

awk '/ is not owned by any package$/ {
  sub(/^file /, ""); sub(/ is not owned by any package$/, ""); print
}' /tmp/rpm-qf-output.txt > /tmp/unowned.txt

unowned_count=$(wc -l < /tmp/unowned.txt)
total_scanned=$(wc -l < /tmp/payload-files.txt)
total_queried=$(wc -l < /tmp/payload-to-query.txt)

if (( unowned_count > 0 )); then
  echo >&2 "ERROR: ${unowned_count} payload files are not owned by any RPM"
  echo >&2 "  (scanned ${total_scanned} total; ${total_queried} queried after allowlist):"
  sed >&2 's/^/  /' /tmp/unowned.txt
  echo >&2 ""
  echo >&2 "These would be missed by the RPM-only SBOM. Either install via dnf,"
  echo >&2 "or — if legitimately non-RPM — add to ALLOWLIST_REGEX in"
  echo >&2 "$(basename "$0") with a justification comment."
  exit 1
fi

echo "OK: all ${total_queried} non-allowlisted payload files (of ${total_scanned} scanned) are RPM-owned."
